deloy vs seft runner

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -61,29 +61,32 @@ jobs:
   deploy:
     name: 🚀 Deploy to Server
     needs: build-push
-    runs-on: ubuntu-latest
+    # runs-on: ubuntu-latest
+    runs-on: self-hosted
     timeout-minutes: 10
     steps:
-      - uses: appleboy/ssh-action@v1
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USER }}
-          key: ${{ secrets.SERVER_SSH_KEY }}
-          script: |
-            set -e
-            CURRENT_IMAGE=$(docker inspect desops_app --format='{{.Config.Image}}' 2>/dev/null || echo "none")
+      # - uses: appleboy/ssh-action@v1
+      # with:
+      # host: ${{ secrets.SERVER_HOST }}
+      # username: ${{ secrets.SERVER_USER }}
+      # key: ${{ secrets.SERVER_SSH_KEY }}
+      # script: |
+      name: 🚀 Deploy
+      run: |
+        set -e
+        CURRENT_IMAGE=$(docker inspect desops_app --format='{{.Config.Image}}' 2>/dev/null || echo "none")
 
-            docker pull ${{ env.IMAGE_NAME }}:${{ needs.build-push.outputs.image-tag }}
-            export DOCKER_IMAGE=${{ env.IMAGE_NAME }}:${{ needs.build-push.outputs.image-tag }}
-            docker-compose down && docker-compose up -d
+        docker pull ${{ env.IMAGE_NAME }}:${{ needs.build-push.outputs.image-tag }}
+        export DOCKER_IMAGE=${{ env.IMAGE_NAME }}:${{ needs.build-push.outputs.image-tag }}
+        docker-compose down && docker-compose up -d
 
-            sleep 20
-            if ! curl --fail --silent http://localhost:8081/actuator/health; then
-              echo "❌ Health check failed! Rolling back to $CURRENT_IMAGE..."
-              export DOCKER_IMAGE=$CURRENT_IMAGE
-              docker-compose up -d
-              exit 1
-            fi
+        sleep 20
+        if ! curl --fail --silent http://localhost:8081/actuator/health; then
+          echo "❌ Health check failed! Rolling back to $CURRENT_IMAGE..."
+          export DOCKER_IMAGE=$CURRENT_IMAGE
+          docker-compose up -d
+          exit 1
+        fi
 
-            docker image prune -f
-            echo "✅ Deploy ${{ needs.build-push.outputs.image-tag }} thành công!"
+        docker image prune -f
+        echo "✅ Deploy ${{ needs.build-push.outputs.image-tag }} thành công!"
